# Generated by Django 2.2.6 on 2019-10-18 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(default=101)),
                ('occupied', models.BooleanField(default=False)),
                ('room_type', models.CharField(default='Deluxe', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guest', models.IntegerField(default=1)),
                ('check_in_date', models.DateField(default=datetime.datetime(2019, 10, 18, 13, 27, 6, 443799))),
                ('checked_in', models.BooleanField(default=False)),
                ('number_of_nights_of_stay', models.IntegerField(default=1)),
                ('checked_out', models.BooleanField(default=False)),
                ('cancel_booking', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Reservation_Management_System.Guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_Reservation_Management_System.Room')),
            ],
        ),
    ]
