# Generated by Django 2.2.6 on 2019-10-18 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Reservation_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 18, 13, 27, 21, 654433)),
        ),
    ]
