# Generated by Django 2.2.6 on 2019-10-19 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_Reservation_Management_System', '0003_auto_20191018_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 19, 3, 32, 27, 468486)),
        ),
    ]
